from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np
import torch
from PIL import Image
from torch.nn import functional as F
from torch.utils.data import Dataset
from torchvision.transforms import InterpolationMode
from torchvision.transforms import functional as TF

from .constants import CLIP_MEAN, CLIP_STD, IMAGENET_MEAN, IMAGENET_STD, REGIONS


def load_manifest(path: str | Path) -> tuple[Path, dict[str, Any]]:
    manifest = json.loads(Path(path).read_text())
    # Accept manifests generated by the pre-release implementation while
    # keeping the public runtime independent of the unpublished paper-ID list.
    for study in manifest["studies"]:
        if "split" not in study and "clean_split" in study:
            study["split"] = study["clean_split"]
    return Path(manifest["data_root"]), manifest


def _rank(study_id: str, seed: int) -> str:
    return hashlib.sha256(f"fgcxr:{seed}:{study_id}".encode()).hexdigest()


def select_studies(
    manifest: dict[str, Any],
    split: str,
    max_train_studies: int | None = None,
    seed: int = 42,
) -> list[dict[str, Any]]:
    if split not in {"train", "val", "test", "all"}:
        raise ValueError("split must be train, val, test, or all")

    if split == "all":
        selected = list(manifest["studies"])
    else:
        selected = [study for study in manifest["studies"] if study["split"] == split]

    if split == "train" and max_train_studies is not None and len(selected) > max_train_studies:
        selected = sorted(selected, key=lambda study: _rank(study["study_id"], seed))[:max_train_studies]
    return selected


def _open_rgb(path: Path) -> Image.Image:
    return Image.open(path).convert("RGB")


def _resize_tensor(image: Image.Image, size: int, interpolation: InterpolationMode) -> torch.Tensor:
    image = TF.resize(image, size, interpolation=interpolation, antialias=True)
    image = TF.center_crop(image, [size, size])
    return TF.to_tensor(image)


def _normalize(image: torch.Tensor, mean: tuple[float, ...], std: tuple[float, ...]) -> torch.Tensor:
    return TF.normalize(image, mean, std)


def _heatmap_mask(heatmaps: torch.Tensor) -> torch.Tensor:
    masks = []
    for heatmap in heatmaps:
        unique = torch.unique(heatmap)
        threshold = unique[max(0, len(unique) // 5)]
        masks.append(heatmap > threshold)
    return torch.stack(masks).float()


class HeatmapDataset(Dataset):
    def __init__(
        self,
        data_root: Path,
        studies: list[dict[str, Any]],
        image_size: int = 224,
        augment: bool = False,
    ) -> None:
        self.data_root = data_root
        self.studies = studies
        self.image_size = image_size
        self.augment = augment

    def __len__(self) -> int:
        return len(self.studies)

    def __getitem__(self, index: int) -> dict[str, Any]:
        study = self.studies[index]
        cached_image = self.data_root / "cache" / f"images_{self.image_size}" / f"{study['dicom_id']}.jpg"
        image = _open_rgb(cached_image if cached_image.is_file() else self.data_root / study["image"])
        cached_heatmaps = self.data_root / "cache" / "heatmaps_224" / f"{study['study_id']}.npz"
        if cached_heatmaps.is_file():
            heatmap_arrays = np.load(cached_heatmaps)["heatmaps"]
            heatmap_images = [Image.fromarray(array) for array in heatmap_arrays]
        else:
            heatmap_images = [Image.open(self.data_root / region["heatmap"]).convert("L") for region in study["regions"]]

        if self.augment:
            angle = float(torch.empty(1).uniform_(-5.0, 5.0).item())
            image = TF.rotate(image, angle, InterpolationMode.BILINEAR, fill=0)
            heatmap_images = [TF.rotate(item, angle, InterpolationMode.BILINEAR, fill=0) for item in heatmap_images]

        image_tensor = _resize_tensor(image, self.image_size, InterpolationMode.BICUBIC)
        heatmaps = torch.stack(
            [_resize_tensor(item, self.image_size, InterpolationMode.BILINEAR)[0] for item in heatmap_images]
        )
        return {
            "study_id": study["study_id"],
            "image": _normalize(image_tensor, CLIP_MEAN, CLIP_STD),
            "heatmaps": heatmaps,
            "masks": _heatmap_mask(heatmaps),
        }


class PredictedHeatmaps:
    def __init__(self, path: str | Path) -> None:
        archive = np.load(path)
        ids = archive["study_ids"].astype(str).tolist()
        self.by_id = {study_id: index for index, study_id in enumerate(ids)}
        self.heatmaps = archive["heatmaps"]

    def get(self, study_id: str) -> torch.Tensor:
        return torch.from_numpy(self.heatmaps[self.by_id[study_id]].astype(np.float32))


class ReportDataset(Dataset):
    def __init__(
        self,
        data_root: Path,
        studies: list[dict[str, Any]],
        predicted_heatmaps: PredictedHeatmaps | None,
        image_size: int = 384,
        feature_size: int = 24,
    ) -> None:
        self.data_root = data_root
        self.studies = studies
        self.predicted_heatmaps = predicted_heatmaps
        self.image_size = image_size
        self.feature_size = feature_size

    def __len__(self) -> int:
        return len(self.studies)

    def __getitem__(self, index: int) -> dict[str, Any]:
        study = self.studies[index]
        cached_image = self.data_root / "cache" / f"images_{self.image_size}" / f"{study['dicom_id']}.jpg"
        image = _resize_tensor(
            _open_rgb(cached_image if cached_image.is_file() else self.data_root / study["image"]),
            self.image_size,
            InterpolationMode.BICUBIC,
        )
        if self.predicted_heatmaps is None:
            cached_heatmaps = self.data_root / "cache" / "heatmaps_224" / f"{study['study_id']}.npz"
            if cached_heatmaps.is_file():
                heatmaps = torch.from_numpy(np.load(cached_heatmaps)["heatmaps"].astype(np.float32) / 255.0)
                heatmaps = F.interpolate(
                    heatmaps[:, None], size=(self.feature_size, self.feature_size), mode="bilinear", align_corners=False
                )[:, 0]
            else:
                heatmaps = torch.stack(
                    [
                        _resize_tensor(
                            Image.open(self.data_root / region["heatmap"]).convert("L"),
                            self.feature_size,
                            InterpolationMode.BILINEAR,
                        )[0]
                        for region in study["regions"]
                    ]
                )
        else:
            heatmaps = self.predicted_heatmaps.get(study["study_id"])
            if heatmaps.shape[-1] != self.feature_size:
                heatmaps = F.interpolate(
                    heatmaps[:, None], size=(self.feature_size, self.feature_size), mode="bilinear", align_corners=False
                )[:, 0]
        maxima = heatmaps.flatten(1).amax(1).clamp_min(1e-6)
        heatmaps = heatmaps / maxima[:, None, None]
        return {
            "study_id": study["study_id"],
            "image": _normalize(image, IMAGENET_MEAN, IMAGENET_STD),
            "heatmaps": heatmaps,
            "reports": [region["sentence"] for region in study["regions"]],
        }


def report_collate(batch: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "study_ids": [item["study_id"] for item in batch],
        "images": torch.stack([item["image"] for item in batch]),
        "heatmaps": torch.stack([item["heatmaps"] for item in batch]),
        "reports": [item["reports"] for item in batch],
    }


def assert_region_order(manifest: dict[str, Any]) -> None:
    if tuple(manifest["regions"]) != REGIONS:
        raise ValueError(f"Manifest region order {manifest['regions']} does not match expected {REGIONS}")
